name: mega
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0-147.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # http
  dio: ^5.4.3+1

  # state management
  flutter_bloc: ^8.1.5

  #Ui
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  infinite_scroll_pagination: ^4.0.0
  flutter_native_splash: ^2.4.0

  # navigation
  go_router: ^13.2.4

  # Others
  freezed_annotation: ^2.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed: ^2.5.2

flutter_native_splash:
  image: assets/icons/ruster/logo.png
  background_image: assets/icons/ruster/logo.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/ruster/
    - assets/icons/vector/
